name: Test Report
on:
  workflow_run:
    workflows: [ 'Pull Request Build and Test' ]
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: 'Tests report'
          path: '**/*.trx'
          reporter: dotnet-trx